### PR TITLE
Bring code tools inline with pcgendev

### PR DESCRIPTION
**Pull request by karianna**

### CODE REVIEW

**Comment by thpr** [comment]
At first glance, this looks more permissive than the current rules (but also brings it up to the new version of PMD).  I will likely provide recommendations to reduce the exceptions

**Comment by karianna** [comment]
@thpr Yes - it matches the existing list at pcgen, happy to work with you to cut down!

**Comment by thpr** [comment]
Eclipse Oxygen reports "This is not a valid PMD rule set configuration"

**Comment by thpr** [comment]
Further investigation indicates the eclipse integration has not yet converted to PMD 6.0.  So I really don't think we should be using it yet until the tools catch up.

**Comment by LegacyKing** [comment]
Six months, any update on this? @thpr @karianna

**Comment by karianna** [comment]
@thpr Latest eclipse is out - is it OK now?

**Comment by karianna** [comment]
Closing this PR in favour of a new one.

**Pull request closed without merging**
