### PR TITLE
Add requireNonNull with a Supplier to defer String building

### PR DESCRIPTION
**Pull request by thpr**

### CODE REVIEW

**Comment by javydreamercsw** [comment]
Is there a way to make Codacy happy?

**Comment by grimreaper** [comment]
Could we implement this in terms of Objects.requireNonNull ?

**Comment by thpr** [comment]
We can't use Objects.requireNonNull unless we universally resolve the get of the supplier, which defeats the purpose

**Comment by grimreaper** [comment]
> We can't use Objects.requireNonNull unless we universally resolve the get of the supplier, which defeats the purpose

I'm not sure I understand:
```
if (object == null)
		{
			return Objects.requireNonNull(object, supplier.get());
		}
```
Has a second null check, but will result in a consistent experience.

Also, I just checked but there is a form of requireNonNull already:
```
public static <T> T requireNonNull​(T obj, Supplier<String> messageSupplier)
```

**Pull request closed without merging**
